3_Layout_View/Models/ErrorViewModel.cs
namespace _3_Layout_View.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

3_Layout_View/Controllers/HakkimizdaController.cs
using Microsoft.AspNetCore.Mvc;

namespace _3_Layout_View.Controllers
{
    public class HakkimizdaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

3_Layout_View/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace _3_Layout_View.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

3_Layout_View/Controllers/IletisimController.cs
using Microsoft.AspNetCore.Mvc;

namespace _3_Layout_View.Controllers
{
    public class IletisimController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

3_Layout_View/Controllers/ReferansController.cs
using Microsoft.AspNetCore.Mvc;

namespace _3_Layout_View.Controllers
{
    public class ReferansController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

3_Layout_View/Views/Iletisim/Index.cshtml
@*
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

     <header>

		<nav class="navbar navbar-expand-lg bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" href="#">Navbar</a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
					<div class="navbar-nav">
						<a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Anasayfa</a>
						<a class="nav-link" asp-controller="Hakkimizda" asp-action="Index">Hakkımızda</a>
					</div>
				</div>
			</div>
		</nav>

	</header>


	<div class="container">
		<h1>Burası uygulamanın iletişimi</h1>
	</div>


</body>
</html>
*@
@{
	Layout = "~/Views/Shared/_Sablon.cshtml";
}


				<h1>Burası iletişim sayfası</h1>

3_Layout_View/Views/Referans/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<h1>Index</h1>